/// Flutter icons IconPack
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconPack
///      fonts:
///       - asset: fonts/IconPack.ttf
///
/// 
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class IconPack {
  IconPack._();

  static const _kFontFam = 'IconPack';
  static const _kFontPkg = null;

  static const IconData fuel = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gauge = IconData(0xf0e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
